#!/bin/bash

echo "arm-none-linux-gnueabi-gcc (Sourcery G++ Lite 2009q1-203) 4.3.3"
echo "Copyright (C) 2008 Free Software Foundation, Inc."
echo "This is free software; see the source for copying conditions.  There is NO"
echo "warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
echo ""
